### ISSUE TITLE
Add support for GitLab

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/cwrc-git-dialogs#11]
There is lots of overlap between github and gitlab protocols. It should be possible to generalize things so that a version of https://github.com/cwrc/CWRC-Git for gitlab could be used to provide gitlab support.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/5de450985f967d34cc15c13ba2fe82f818c859ac
https://github.com/cwrc/cwrc-git-dialogs/commit/da186ca861e71ce1c9204569351b7f3efe4f68dc

**Comment by ilovan** [comment]
Is this for Leo (Bucknell), Bryan (Texas A&M) or Timo (Mainz), @ajmacdonald ? did we ever get confirmation that it works as expected?

**Comment by ajmacdonald** [comment]
This was primarily for Timo I believe. I never achieved feature parity with GitLab but I think it worked well enough for his purposes.

**Comment by ilovan** [comment]
sounds good - will close for now then, assuming that the changes you made to the code to facilitate that will propagate to master with the push to production
