### ISSUE TITLE
repositories can only be created in the authenticated user's account, not in an organization account

### ISSUE THREAD

**Issue by jchartrand** [cwrc/cwrc-git-dialogs#19]
## Expected Behaviour
Might want to look at extending it to allow creating repositories in an organization account for which the authenticated user is a member.

## Current Behaviour
repositories can only be created in the authenticated user's account, not in an organization account

## Possible Solution
We are using version 3 of the Github API, but version 4 (GraphQL) also doesn't seem to allow creating repositories in an organization.  If we wanted this, we might have to look at GithubApps.

**Comment by ilovan** [comment]
this is fixed on dev-cwrc-writer
