### ISSUE TITLE
GitWriter all search results and browsing listings should be limited to xml documents. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-git-dialogs#20]
## Expected Behaviour
Users should see in the expanded browsing view of a repository and in the search results only xml documents. Repositories that don't contain any XML documents should not show up at all.

## Current Behaviour
Users can see and click on any type of file in any repository. (if the file is not xml, the GitWriter still opens in "blank", with no warning or error message)

## Possible Solution
Check for 
```<?xml version="1.0" encoding="UTF-8"?>``` at the top of each file and show only the hits?

**Comment by SusanBrown** [comment]
I would say let's leave it and rely on users to filter what they own or have access to using search. 

However, in deciding what I thought about this I've discovered that search doesn't seem to be working. Will create a separate issue for that.
